### ISSUE TITLE
Thumbnails are showing broken in media viewer

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1050]
**Describe the bug**
Thumbnails are showing broken in media viewer
Login to AchalaB@rwbnitiuat 
click on media viewer
you can see the broken tumbnel

**To Reproduce**

1. Login to AchalaB@rwbnitiuat 
2.click on media viewer
3.you can see the broken thumbnail
4. On clicking the broken thumbnail image gets loaded

**Expected behavior**
Thumbnail should show up

**Cloudwatch logs:**
```Something went wrong installing the \"sharp\" module\n\nCannot find module```

But the lambda zip in avni-lambdas s3 bucket has sharp node module.

**Analysis details**
In rwbnitiuat folder inside prod-user-media, on Sep 29, 4 media are available, but inside prod-user-media/rwbnitiuat/thumbnails - there are no images generate on Sep 29 though lambda trigger of S3CreateEvent is available on prod-user-media.

![Image](https://github.com/avniproject/avni-webapp/assets/10369963/a6977e6a-af99-4a4a-81fd-a9ab4e2f4c27)

**Comment by 1t5j0y** [comment]
Instant thumbnail lambda has been broken since Aug 21 (4.0 release) when the lambdas were last deployed. Looks like incorrect node version was used when it was built during 4.0 release. Builds fine on macs with correct node version.

Redeployed the lambdas to staging, prerelease and prod just now and it is working fine now.

We will need to come up with some solution to create thumbnails for the images uploaded between Aug 21 and today

**Comment by mahalakshme** [comment]
@1t5j0y have created a card for the above: https://github.com/avniproject/avni-media/issues/161
