### ISSUE TITLE
Invalid CSV type error

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-webapp#1192]
**Describe the bug**
On uploading a valid CSV type file, you get an error saying "Select a valid CSV type file"
This is caused by an extra symbol in the values of the file that contained the degree symbol °.

**To Reproduce**

1. Create a CSV file for any sample org
2. And under location properties, for the values of latitude and longitude, have the degree symbol °.
3. On trying to upload, you should get the error.
Refer to the attached file for an example.

[WB location_Uploads Fromat (1).csv](https://github.com/avniproject/avni-webapp/files/14926850/WB.location_Uploads.Fromat.1.csv)

**Comment by mahalakshme** [comment]
@Gojo-Taqi this is already dealt in https://github.com/avniproject/avni-product/issues/1531

**Comment by Gojo-Taqi** [comment]
@mahalakshme I don't think the issue should be closed.
Even with this card, https://github.com/avniproject/avni-product/issues/1531, it doesn't say anywhere that on adding the degree symbol, the csv will not break.
Or maybe it is handling and not mentioned in the card.

**Comment by mahalakshme** [comment]
@Gojo-Taqi What needs to be AC I would like to decide. The issue here is users have added coordinates with degree. Currently in sample file there is no sample for coordinates. So there is no way for users to understand currently the format for coordinates. I think some things we can understand only iteratively. In the card I have mentioned this ```--- degree - solved by data in sample file```
