### ISSUE TITLE
Images UI is broken when looking at previous encounters

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#1220]
### How to reproduce
- Add an image as part of an encounter
- Save the encounter with image
- View the Subject Dashboard and try to scroll up and down
- Notice that the Previous Encounters header shows up above the image

<img width="938" alt="image" src="https://github.com/avniproject/avni-webapp/assets/344222/e56e184e-ae32-4817-b41f-ca766e20bc3f">

**Comment by himeshr** [comment]
After fix
https://github.com/avniproject/avni-webapp/assets/72493481/77b1269f-7732-4bd2-ab61-83c99592acb9

**Comment by Dinesh2019** [comment]
On the registration page and also in enrollment page, an overlap issue occurs and image is not displayed correctly.The image and content appear to be overridden 

<img width="1710" alt="Screenshot 2024-06-06 at 5 59 17 PM" src="https://github.com/avniproject/avni-webapp/assets/127730126/38f08923-a233-4483-a786-cd2f178afa00">

**Comment by AchalaBelokar** [comment]
- [ ] I try to edit the register with image is having multiselect I try to upload image there it is failing there. Login with AchalaB@rebnitiuat
- [ ] just try to edit registration  workorder.

**Comment by 1t5j0y** [comment]
@AchalaBelokar it looks like the 'Image 1 of the site' field was previously a single select and it has been changed to multiselect and hence this issue is happening for existing records. It does not happen for newly registered work orders.

@mahalakshme do we already have a card to prevent changing of form element type from single to multi or vice versa and if so, can we prioritise it?
