### ISSUE TITLE
New screen to manage privileges

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#272]
- Ability to create a new user group.
- On clicking a particular group it shows list of all the users who are part of that group in one tab.
- In permission tab there will be some short-hands for quick privileges. And below that list of all possible privilege for that organisation in a tabular form (Allow, PrivilegeName, EntityName).
- User can Allow or Revoke any privilege. Dependent privileges should also get select/unselect based on what user select.

**Comment by garimadosar5** [comment]
QA Notes - 
- On permission page, user has to go for each and every form and activity in terms of providing information.
-

**Comment by 1t5j0y** [comment]
> Voided subject types are also showing in the list of permissions.
Expected behaviour as clarified separately.
> For non admin users, it should not show the option of adding subject type or voiding subject type etc.
Only admins have access to the privileges screen.
> In permission user cannot register an individual but on the client I am able to register the individual.
Perhaps, testing happened on an apk without these changes as this finding was raised before the apk was provided.
> If I am setting some permission in enrollment, it takes me to the "ENTITY TYPE: Encounter" or "ENTITY TYPE: Subject" without poping any message. The list is so long I cannot figure out where it has taken me.
> On permission page, user has to go for each and every form and activity in terms of providing permission.
> There are some permissions that are dependent on other permissions so if we can have some hierarchy of permissions that would be less confusing for user when the user is setting up the permissions. 
The UX for this screen is complex due to number of privileges and dependencies between them and the various entities. The jumping around was happening due to the dependent privileges. Made some minor improvements and continuing to work on this while the core functionality for this feature is being tested.
