### ISSUE TITLE
add IndividualEncounterCancellation formtype in system

### ISSUE THREAD

**Issue by swapnil106111** [avniproject/avni-webapp#291]

**Comment by swapnil106111** [comment]
@garimadosar5  You can create the form with IndividualEncounterCancellation type in forms tab.

**Comment by garimadosar5** [comment]
QA Notes - 
- When I am creating an IndividualEncounterCancellation In "Encounter type section", it gives the option of Program encounter also.
![Screen Shot 2020-04-11 at 8.23.44 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/1f448724-3db4-4689-a747-b15dafdd773f)

Here "Anthropometry Assessment" is Program encounter, not General encounter.
- Also, I guess we should name it as general encounter cancellation because we can have the cancellation for any other subject type also. eg: Waterbody type subject.

**Comment by swapnil106111** [comment]
@garimadosar5  We will keep this as it is for now.

**Comment by vinayvenu** [comment]
@garimadosar5 the option to provide encounter types has been removed. I guess this card is not relevant anymore? Closing this card.
