### ISSUE TITLE
Translations getting overridden

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-webapp#416]
**Describe the bug**
Translations like name and Subject Type are sometimes getting overridden. E.g. name is getting overridden with Household Number.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Analysis**
It is getting overwritten in the platform_translation table itself against platform type Web. We need to find out who is overwriting it.

**Comment by vindeolal** [comment]
Right now the issue is not reproducible, we have added audits on the platform translation table to check which user is overwriting the translations. We have also set-up a Metabase alert whenever a name key in the platform translation changes to Household number. 
https://reporting.avniproject.org/question/976

**Comment by vindeolal** [comment]
The issue was with the GET API of web translations. We were directly updating the platform translation Persistent object due to which platform translations were getting updated. 
https://stackoverflow.com/questions/8190926/transactional-saves-without-calling-update-method
Fixed the code, and have added the test cases.

**Comment by hithacker** [comment]
@garimadosar5 
Steps to QA:
1. Go to a sample implementation. Download the translations file. In the file change the value of some of the translations like “name”, “age” and upload the file with Platform Web. Go to data entry app and see that translations are being overridden.
2. Logout and go to another sample implementation. Go to data entry app and see that the base translations are not getting overridden on UI.
