### ISSUE TITLE
Metadata zip upload failed (blocker)

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-webapp#429]
**Describe the bug**
Metadata zip upload failed

**To Reproduce**
1. Go to app designer and download implementation bundle with locations for Sewa Rural Old organisation.
2. Create a new organisation or use organisation Adolescent demo backup 2 org.
3. Go to admin, upload. Try uploading the zip file by choosing metadata zip
4. See an error in the attached file

[errors-Sewa Rural Old.csv.zip](https://github.com/avniproject/avni-webapp/files/4824985/errors-Sewa.Rural.Old.csv.zip)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by arjunk** [comment]
This is happening because Sewa-Rural inherits from openchs and in bundle downloads those subjectTypes and concepts from openchs org are not coming. Due to which it is failing during the upload. We have deprecated the inheritance feature. 
Closing this as this is a data issue and not a product issue.
