### ISSUE TITLE
Enrollment (Edit, Exit, ...): Pending work of [Review comment on Barnch [exit-edit-enrolment-27-may]]

### ISSUE THREAD

**Issue by SaketKumarPSL** [avniproject/avni-webapp#439]
Comment:- Hiren told after resolving the review comment (Review comment on Barnch [exit-edit-enrolment-27-may]) to check all workflow of enrollment functionality included 
1. New enrollment
2. Edit enrollment
3. Exit enrollment
4. Edit Exit enrollment
5. Undo enrollment
but at that time we are working on Estimate So I pause this work also hiren already approved PR for (Review comment on Barnch [exit-edit-enrolment-27-may]). So we can create one new card for it that is the second point I mention in the mail.

**Comment by eshwarjoshiPsl** [comment]
1. Not Able to Create New Enrollment, loader is showing there.
2. On reload, subject Uuid not found, because of "formwizard" common component use in all workflow forms and its store in State.
3. The first time on a click on exits or edit form its come to direcly Dashboard page.
4. Save is not happening sometimes.
5. sometimes not able to select the input field like radio and checkbox.
