### ISSUE TITLE
Transaction object to subject association via web app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#473]
App Designer changes to handle new data types.

**Comment by 1t5j0y** [comment]
- [x] Update existing calls to /organisationConfig to use PUT instead of POST
- [ ] Update app designer screens to handle new data types
- [ ] Concept creation/editing - For Location datatype, render keyvalues differently to display and edit new `isWithinCatchment` and `lowestAddressLevelType` attributes
- [ ] Concept creation/editing - For Subject datatype, Render keyvalues differently to display and edit new `subjectType` attribute

**Comment by 1t5j0y** [comment]
Dev box feedback:
- [ ] Location - config should be within catchment by default. 
- [ ] Show lowest address level as default if there is just one hierarchy.
- [ ] Update concepts documentation linked on the right of the concepts screen.
- [ ] Add the new datatypes to Inline concept creation.
- [ ] Update edit views to show the attributes for already created concepts.
