### ISSUE TITLE
[DEA] Error is not showing up immediately on selection of unique answer. It only shows up when user presses Next. 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#534]
- In the case of unique answer the error shows when user presses next.
- The error should be shown as the user select the option. (View filter rule).

**Comment by hithacker** [comment]
@1t5j0y Don't pick this up as it will get covered in the refactoring.

**Comment by 1t5j0y** [comment]
Moving this card to the P1 bugs epic as this is being clubbed with #525.

**Comment by hithacker** [comment]
We may not fix this right now as it requires quite a bit of refactoring and it does not look like a blocking issue.

**Comment by hithacker** [comment]
### Why this card needs refactoring?

We are doing validation inside updateObsWorker listener that we have in pretty much every saga. Inside here the code to update the observations and validation is there but in two separate methods. The code to update the observations uses obsHolder and depending on the data type of the concept it uses if-else logic to call a different obsHolder method. But the validation is being done incorrectly because we are just passing the user input value to the formElement.validate method while it's expectation is to get passed an observation model in case of non-primitive values. So it's not doing this validation and so the user is allowed to select the unique answer with another answer. To fix this, we need to pass the updated observation that obsHolder returns to the validate method. But because of the way the code to update and validate is split into different methods, it's not possible to do this without resorting to repeating if-elses inside the validation method also. It will be better if we put this code of having to update and validate in a single method as we do it in avni-client and have the if-elses in a single place(either in a component or a single util method that calls a different method to update and validate depending on the concept type).

**Comment by garimadosar5** [comment]
QA Notes - 
Not fixed.
![Screen Shot 2020-12-16 at 5.04.10 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/347783e6-d869-44d9-8b9b-4695b13c84eb)

**Comment by hithacker** [comment]
@garimadosar5 Working fine for me on staging - same case as above. Maybe it wasn't deployed when you tested. Please try again.
