### ISSUE TITLE
[Bug] DEA and App designer - Pre-release testing

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-webapp#572]
- Cannot create Group and household subject types from app designer.
- Relationship type and group role is giving the error in bundle upload. 
relationshiptype.json and grouprole.json

**Comment by 1t5j0y** [comment]
1. Cannot create group and household subject types from app designer - Fixed
2. Relationship type bundle upload error - bundle contains records with same uuids for different rows
3. Group role bundle upload error - Same root cause as 1. Fixed.

Root cause for the fixed issue was an unnecessarily renamed variable in GroupRoleContract.
