### ISSUE TITLE
"Refresh status" not updating upload status under admin Upload menu

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#829]
"Refresh status" button is not updating the status of the upload. Basically during a demo we uploaded Lahi UAT bundle to LAHI training organisation and it dint update the upload dashboard.

**Comment by nupoorkhandelwal** [comment]
[https://app.zenhub.com/files/172675608/3fd322b2-3e87-4ca3-85ab-c054c1b9f0fe/download](https://app.zenhub.com/files/172675608/3fd322b2-3e87-4ca3-85ab-c054c1b9f0fe/download)

**Comment by petmongrels** [comment]
The operational modules are not loading because organization config has custom registration locations for a subject type. the location type for this subject type has not been imported via metadata zip upload. This is because in metadatazip we are not putting location types.
Fixed it by including location type always.
