### ISSUE TITLE
In "App Designer", unable to generate rule with skip-answers and value for single condition

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-webapp#843]
![Screenshot 2022-12-01 at 11.02.30 AM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/539e0b25-f93b-4cd6-902e-c5aca33cd856)
![Screenshot 2022-12-01 at 11.01.54 AM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/8d13d690-534b-4017-900c-28a65385ff6e) 

In Avni Web-app "App Designer", we are unable to configure a rule on Single-select / Multi-select fields to secify both "skip-answers" and "value" at the same time.

The issue is that in the app designer, we can specify both "skip-answers" and "value", but on clicking "Validate and generate rule", only one of the 2 actions is included in the condition.

In the attached screen-shots, we have specified both actions both "skip-answers" and "value", but the on condition13 being true, only one of them, i.e "skip-answers" is included.

**Comment by petmongrels** [comment]
@shivamragnar The functionality is working. But it is not clear to me why a new action should be added on onValidateAndGenerateRule. A new action empty should get added when the user is adding a new action - not sure why this is being done on validate.  Can you please provide some details on what you saw in the code as the behavior and how this fixes it? It is not obvious.

**Comment by shivamragnar** [comment]
So, what i changed was, there was a bug in the app where you cannot add subsequent actions in the rules when clicked on validateAndGenerate, I fixed that. The bug in the card was then stopped appearing. That is what was happened. 
Now I investigated it, seems like some issue in the reducer, haven't yet figured out the issue but I am sure it's there because the state that gets set in the local component is not correct.
