### ISSUE TITLE
[PoWER] Task assignment screen - Dropdown for  Task status filter is empty

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#864]
To reproduce Staging - Power UAT organisation

![Screenshot 2022-12-29 at 4.04.00 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/5d2f34d6-4ef8-444d-b102-8a83810ee21c)

* when I am trying to filter Task status no options.
* When there are multiple task types, show the Task Status dropdown disabled

**Comment by mahalakshme** [comment]
@AchalaBelokar @petmongrels has coded such that task status dropdown is not disabed, but shows all options, which is different from the acceptance criteria u ve mentioned. I feel we should show all options, since user might want to filter by task status alone, but not task type. Hence moving this to ready for QA.
