### ISSUE TITLE
[avni-webapp] getObservationReadableValue not working on DEA

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#875]
https://avni.freshdesk.com/a/tickets/2350

As mentioned in the support ticket, since getObservationReadableValue is present on program eligibility for HH , clicking on hh subject is giving error on DEA.
getObservationReadableValue is not working on the DEA even within forms.

  ![Screenshot 2023-01-12 at 2.58.31 PM.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/494cec9d-944d-42a0-8ab9-dfa3ea9f9840)

**Comment by 1t5j0y** [comment]
This is not related to getObservationReadableValue. This is failing because of completely commented out eligibility rules for "Solild waste managment" and "Water supply" programs in Shelter UAT. If those rules are completely deleted instead of being commented, it works.

Implementing https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/rules-server/34 so app flow does not break for rule failures.
