### ISSUE TITLE
Search issue - cursor gets out of focus

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#889]
https://avni.freshdesk.com/a/tickets/2324

To reproduce --
1. Go to Web console
2. Go to Admin
3. Select Users from left hand panel
4. Try searching a user by some search string, as soon as we pause while adding the search string the cursor gets out of focus.

**Comment by vinayvenu** [comment]
@nupoorkhandelwal is this an avni-webapp story or avni-client?

**Comment by nupoorkhandelwal** [comment]
@vinayvenu This is in webapp.

**Comment by SamarthBagga** [comment]
Hi @vinayvenu I have managed to isolate the issue to the organisation prop being passed using WithProps to the UserList in the file OrgManager.js. Upon removing this prop and then removing the subsequent instances when the prop is used in the UserList component definition, the text inputs work as they should(i.e. they do not get out of focus and the cursor doesnt dissapear). 
But I don't think that this is an optimal solution. Thus could you guide me as to why this organisation prop is causing this problem as I have'nt been able to identify the root cause of the problem with the organisation prop?

**Comment by vinayvenu** [comment]
@SamarthBagga this is not related to the WithProps at all. If you look at the [UserFilter](https://github.com/avniproject/avni-webapp/blob/master/src/adminApp/UserHelper.js#L36), the component clears out the input when the search is complete and results are out. This component belongs to react-admin, so we cannot change that behaviour. We need a different component that does not clear the form fields when the search is complete. 

See documentation here - https://marmelab.com/react-admin/doc/2.9/List.html#filters

**Comment by SamarthBagga** [comment]
@vinayvenu , on further analysis, it appears that the problem specifically arises in the UserFilter due to the utilization of organization props, whereas other sections, such as the Locations section, employ similar filtering methods without encountering this issue.

**Comment by vinayvenu** [comment]
@SamarthBagga good catch. I am not sure why this is happening. The organisation prop is necessary on that screen because it is used to filter users by the specific organisation (remove superadmins etc).

**Comment by vinayvenu** [comment]
@SamarthBagga were you able to make any headway into this one?

**Comment by SamarthBagga** [comment]
@vinayvenu i am still working on it, but it seems like component is being re rendered causing it to make duplicate api calls. The console.log when I enter text in the text input of the users section looks like this -
![image](https://github.com/avniproject/avni-webapp/assets/69239707/2a733f5c-dbe5-46ff-98d4-740509ca1839)

where as for the locations section text input it looks like this -
![image](https://github.com/avniproject/avni-webapp/assets/69239707/71861732-8f24-4462-b366-33b9d8444d57)

I am still working on this and I'm sure I'll be able to come up with a fix.

**Comment by mahalakshme** [comment]
untagging release since it is a good first issue and not of immediate priority

**Comment by vedfordev** [comment]
## Analysis :

### Reason :
1. I provide log in **render** method and applied **componentDidUpdate** method with log in **OrgManager.js**. I found that when we provide input, OrgManger component is gettingUpdated and again render. SO, It is causing memory leak issue. I think it may be because of propdrilling.


### Proposed Solution :
1. We can use **useContext**. So it removes prop drilling and we get organisation in UserList.
2. We can also use **shouldComponentUpdate** in OrgManger and check if org.id is same then skip the component update. 


@vinayvenu / @himeshr  Check and let me know.
