### ISSUE TITLE
Sync concept dropdown on subject settings do not give an option for Decision concepts.

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#892]
For example, in APF we have a decision concept "High risk" but it doesn't come in the Sync attribute dropdown on the subject settings. Ideally, decision concepts should come in the dropdown.

### As is:
Currently on a subject type we show only coded, numeric and text concepts that are mandatory as sync registration concepts.

### AC:
Show decision concepts that are of type coded, numeric or text concepts as well in the 'sync registration concepts' dropdown. When a decision concept is selected show a alert message stating 'Make sure to set the value of the selected decision concept to sync the subject to mobile app'

### Technical input:
decision_concept table

**Comment by vinayvenu** [comment]
@mahalakshme this is already fixed, right? Close this card?

**Comment by mahalakshme** [comment]
@vinayvenu Its still an issue

**Comment by vinayvenu** [comment]
@mahalakshme if the concept is part of the form's decision concept, then it will show up as a sync attribute. I had verified this. Is there another problem?

**Comment by mahalakshme** [comment]
@vinayvenu No it doesn't work. I think in prod they have manually inserted into the db via SQL. The below is in prerelease after removing the entry from db. 

<img width="1279" alt="Screenshot 2024-03-29 at 6 18 18 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/9551fcdd-427d-4ae9-ae7f-246caab485b8">

We currently display only mandatory Text, coded, and numeric fields in the dropdown to avoid sync issues. Considering that wondering how will we handle for decision concepts. May be we should just show a warning when a decision concept is chosen as 'sync registeration concept' to user so that they makes sure it is set to some value in decision rule.

**Comment by dinesh2096** [comment]
If we give sync concept between user and subject type 


https://github.com/user-attachments/assets/0e739f89-295d-43bb-a341-1cea107c22e6

**Comment by dinesh2096** [comment]
QA Reference video : 


[Click here to watch the video](https://drive.google.com/file/d/1eatsAY2CCkkorwMZjvmjf3e_WD2MeYfh/view?usp=drive_link)

**Comment by dinesh2096** [comment]
- [ ] Test the decision rule by adding the concept which has code numeric and text and validate it is displaying in the sync concept in the subject type
- [ ] Test the decision rule by adding the concept which other than  code numeric and text and validate it is not displaying in the sync concept in the subject type
- [ ] Test by without adding the concept for decision rule and validate it is not showing in the sync concept.
- [ ] Test by removing the decision concept  and validate in the sync concept is removed in the subject type.

**Comment by dinesh2096** [comment]
Found a issue : 

- [ ]If we delete the concept in the decision rule, it still appears in the subject type. However, when we click on "Edit," the synced concept is no longer visible.
