### ISSUE TITLE
Creating front page for listing images

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#905]
Create a screen to show the listing of all the available images. 
- Create the necessary API to fetch the images from the database.

##### Acceptance Criteria:
1. Images are listed in grid view, with thumbnails.
2. There is option to select one or more images, using checkboxes.
3. There would be pagination option to navigate through pages.

**Comment by petmongrels** [comment]
Some of it is are general comments and not necessarily related to this, but since this is the first card I am reviewing I am putting them down here.
- add .nvmrc file with the appropriate node version (we use the latest LTS version)
- hopefully, the process configuration is temporary. we should load these from the server. if something is missing do let us know we will add.

**Comment by petmongrels** [comment]
Any update on this?

**Comment by brajesh-lab** [comment]
@petmongrels Please see my responses below:

- .nvmrc file added.

- Yes, the process configuration  is temporary  for development  right now, it will come from the server 

- I'll move the CSS stylesheet to a separate file, under the [task](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-media/44)

- The Makefile is only for the script right now, for others I'll add a new story

**Comment by Dinesh2019** [comment]
we can remove the # from images per page 
Excepted : Images per page 
Actual : #images per page 
/home/dinesh/Pictures/Screenshots/Screenshot from 2023-05-04 15-56-34.png

**Comment by rudresh** [comment]
@Dinesh2019 I've made the updates. Please check.
