### ISSUE TITLE
View messages to a subject

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#916]
### Story

As an admin, I should be able to see the messages sent to a subject so that I can decide to send a message to that subject.

We will be focused on implementing screen 5, 6 and 7 in this story.

### Acceptance criteria

- A new menu item - "Subjects" is present in the Whatsapp messages home screen
- On clicking, the Subject Search widget is available to the user. This is the same widget currently available on the Data Entry Application (screen 5)
- On clicking Search on the Subject Search widget, the user is presented with a Subject Listing, out of which they can choose one user (screen 6)
- When choosing a user, the user is taken to the "Subject" screen that contains scheduled and sent messages to that subject (screen 7). The message widgets are the same as what is available on the Data Entry Application.

UI mockups - https://docs.google.com/document/d/1GtlITrqW5hXHjHI9PHWkBi07OiWP1ZN8ycRsRzgz9-o/edit?usp=sharing

**Comment by himeshr** [comment]
@vinayvenu , i think the requirement is not clear here, did you intend for subject DEA screen in entirety to be shown or just the Messages Section as part of pane(7) in mockups for this task.?

**Comment by vinayvenu** [comment]
@himeshr just the messages section (same as what we discussed, and as shown in the mockups).

**Comment by himeshr** [comment]
Okay, this needs more work then.. currently the entire Subject Details DEA screen is shown.

**Comment by petmongrels** [comment]
The handwriting and drawing on the mock up is very difficult to understand. From screen 7 I couldn't make out whether it is a new screen or existing screen poorly drawn

**Comment by mahalakshme** [comment]
@petmongrels  I feel MessagesView from SubjectDashboardTab in DEA can be removed. @vinayvenu am I right? If this is the case, MessagesView can be moved within whatsapp folder.

**Comment by mahalakshme** [comment]
@petmongrels I feel on selecting a subject from search, url should have subject id in url path param like in groups, so that on refresh, new scheduled messages if any can be seen.

**Comment by petmongrels** [comment]
1. I am leaving it there, in case there is usage in the future. I think because different people are playing different stories we are doing the same things differently
3. It is a tradeoff between page refresh and single page app. I thought the user may want to quickly browse multiple subjects and refreshing will slow the user down.
4. I have kept it Open because there could be a number of actions on that screen, in the future so we cannot keep describing all actions via the button.
5. I am not able to reproduce this.

**Comment by AchalaBelokar** [comment]
- [ ] scheduling messages not visible

**Comment by petmongrels** [comment]
Are they visible from the data entry app for the same subject?

**Comment by AchalaBelokar** [comment]
- [ ] Not showing the all subject list. Suppose  there currently 50 subject but it is showing the 20 subject

**Comment by petmongrels** [comment]
All the places where from the SearchSubject is used in embedded form - find relative, adding subject to contact group, and searching subject to view messages - there is no pagination. The later two have happened because it is using the the embedded version from find relative. The idea in find relative being - the user will narrow down their search instead of paginating through results.

If we want pagination in this we should play a separate story.
