### ISSUE TITLE
Implement CI in media-viewer app

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#927]
- [x] Setup avni-media-client to work in staging env
- [x] Setup DB for avni-media
- [x] Init config for client and server on the ec2-instance
- [x] Setup latest frontend app for avni-media
- [x] Setup backend server app for avni-media
- [x] Configure circleCI config in avni-media
- [x] Automate deploy of avni-media-client to target machine
- [x] Automate deploy of avni-media-server to target machine
- [x] Configure prod and non prod contexts to restrict deployment privileges as done in https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-product/1321

## Important note:
 - Build happens at once for both server and client and artificats are created for both Staging and Prod environments
 - During deploy, we only have to choose the relevant env client and server artificats and deploy them both
 - Client and server are both deployed as PM2 processes in avni-media-user UserContext on IntegrationServer EC2 machine

#Config for reference

## Client-config:
NEXT_PUBLIC_IMAGE_LIST_URL=https://localhost:6013/etl/media
NEXT_PUBLIC_DOWNLOAD_REQUEST_URL=http://localhost:3010/media-viewer/requestDownload
NEXT_PUBLIC_DOWNLOAD_LIST_URL=http://localhost:3010/media-viewer/allData
#http://localhost:3010 === NESTjs

## Server-config:
AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY}}
AWS_SECRET_ACCESS_KEY={{AWS_SECRET_KEY}}
S3_BUCKET_NAME={{STAGING/PROD_S3_BUCKET_NAME}}
S3_ZIP_UPLOAD_BUCKET_NAME={{STAGING/PROD_S3_BUCKET_NAME}}
AWS_REGION={{AWS_DEFAULT_REGION}}

DB_HOST={{STAGING/PROD_DB_HOST}}
DB_PORT={{DB_PORT}}
DB_USERNAME={{DB_USER}}
DB_PASSWORD={{DB_PWD}}
DB_DATABASE={{DB_DB}}

**Comment by vinayvenu** [comment]
@himeshr 

1. Why do we use circleci/openjdk:11-jdk for the deploy job? 
2. Ideally, the work of configuring the server (installing software) should have been handled in avni-infra, and the CI should just hand over the responsibility to Ansible. See [here](https://github.com/avniproject/avni-etl/blob/main/.circleci/config.yml) on how we did this for avni-etl. By doing it this way, we can be sure that the scripts on Ansible are being used. Right now we are missing this functionality on the avni-infra repository, and have another version on the avni-media repository which will need to be removed later


Since this is working, we can keep it while I create a card to fix this.

**Comment by himeshr** [comment]
Made the change to use 'cimg/node:19.8.1' for the deploy job.
