### ISSUE TITLE
Create zip file for selected images

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-webapp#942]
When user selects images and clicks download a zip file should be created. The zip file should take care of the  structure mentioned [here](https://gist.github.com/vinayvenu/eabbb7c376e32f5bf665c7a0b595f524)

Task:
- Download the selected files from S3 on the server
- Create the directory structure 
- Create the zip file
- Upload the zip file in S3
- Update the database with the zip file S3 URL
- Delete the downloaded images and other files created temporarily for zip file creation.

**Comment by rudresh** [comment]
This card is not covering the directory structure of images in the zip. It will be covered in https://github.com/avniproject/avni-webapp/issues/956

**Comment by rudresh** [comment]
@petmongrels this commit has the changes https://github.com/avniproject/avni-media/commit/11beca648352d93613ec3fc3ed404468d333634d

**Comment by petmongrels** [comment]
- we should use material ui and react components instead of generating HTML by hand. Material UI handles many styling issues and it is much lesser code to maintain. This code will be very difficult to maintain in future.
- what is the reason for using localStorage instead of react state management mechanisms. there are very few things 
- no unit test for getFileSizeText method (this method should be moved to domain layer ideally)

**Comment by brajesh-lab** [comment]
@petmongrels Please see my responses below:
- We are using Tailwind CSS. A lot of code clutter is due to inline CSS. I'm planning to address this feedback under the [task](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-media/44). We have used the react component at most of the places. 
- I am not using localStorage in the commit that I shared. Could you tell me where you are seeing this? I've used localStorage in another task where I had to call the location component recursively. In there the React state was getting wiped out when a new component was rendered. 
- I'll move a unit test for this.

**Comment by petmongrels** [comment]
The usage of localstorage in - LocationHierarchy.tsx

**Comment by brajesh-lab** [comment]
I have written unit test cases for folder structure as well as getFileSizeText in this [ commit ](https://github.com/avniproject/avni-media/commit/2772fd5e2de8ef780c74a2d2e593caee8453319e)

**Comment by rudresh** [comment]
@petmongrels @vinayvenu Could you review this and provide your feedback.

**Comment by petmongrels** [comment]
- the unit tests and code is fine now
- I still see this on the latest.
localStorage.setItem("secondLevelTypeId", secondLevelTypeId.toString());

- please also add a makefile target for running unit tests (unrelated to this card)

@rudresh @brajesh-lab

**Comment by petmongrels** [comment]
I don't see any new commit in avni-media
the local storage code is still there

**Comment by brajesh-lab** [comment]
@petmongrels 
I have removed the local storage usage with the issue in cart no #62. Commit is [here](https://github.com/avniproject/avni-media/commit/3cf2f64656570c15125205e3fc468adda1522c7e). Please take a look.

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-06-06 at 8.07.43 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/c41390f8-06c7-4281-9062-e6320e0d443f)concept is overlapping on the comment type

**Comment by AchalaBelokar** [comment]
- [ ] No delete option is present in download window

**Comment by rudresh** [comment]
@AchalaBelokar Delete option was not needed. I had put that initially but after discussion with @vinayvenu took it off. @vinayvenu Could you comment here.

**Comment by rudresh** [comment]
@AchalaBelokar Delete option was not needed. I had put that initially but after discussion with @vinayvenu took it off. @vinayvenu Could you comment here.

**Comment by vinayvenu** [comment]
@rudresh thats right. We don't need a delete option, atleast right now.
